"""Render the README's results tables from `results/*.json`.

The README contains marker comments:

    <!-- BENCH:BEGIN --> ... <!-- BENCH:END -->

Everything between them is generated. Nothing else writes a performance number
into the README, which means a figure in that file cannot exist without a JSON
run behind it, and `make report` regenerating clean is a check that the two
still agree.

    python -m hag.report            # rewrite README.md in place
    python -m hag.report --check    # non-zero exit if it would change
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

BEGIN = "<!-- BENCH:BEGIN -->"
END = "<!-- BENCH:END -->"

REPO = Path(__file__).resolve().parents[2]


def load_runs(results_dir: Path) -> list[dict]:
    runs = []
    for path in sorted(results_dir.glob("ops_*.json")):
        runs.append(json.loads(path.read_text()))
    return runs


def _env_table(runs: list[dict]) -> str:
    lines = [
        "| device | backend | datasheet BW | measured copy BW | % of datasheet | dispatch floor |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for run in runs:
        dev = run["device"]
        spec = dev.get("spec")
        sheet = f"{spec['peak_bandwidth_gbs']:.0f} GB/s" if spec else "n/a"
        pct = (
            f"{100 * run['measured_copy_gbs'] / spec['peak_bandwidth_gbs']:.0f}%"
            if spec
            else "n/a"
        )
        floor = run.get("dispatch_floor_ms")
        floor_s = f"{floor * 1e3:.0f} us" if floor else "n/a"
        lines.append(
            f"| {dev['device_name']} | {dev['backend']} | {sheet} "
            f"| {run['measured_copy_gbs']:.0f} GB/s | {pct} | {floor_s} |"
        )
    return "\n".join(lines)


def _results_table(runs: list[dict], regime: str) -> str:
    lines = [
        "| device | op | shape (rows x width) | baseline | fused | speedup | eff. BW | % of measured peak |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    any_row = False
    for run in runs:
        name = run["device"]["device_name"]
        for r in run["results"]:
            if r["regime"] != regime:
                continue
            if regime == "prefill" and r.get("dispatch_bound"):
                continue
            any_row = True
            lines.append(
                f"| {name} | `{r['op']}` | {r['rows']} x {r['width']} "
                f"| {r['baseline_ms']:.3f} ms | {r['fused_ms']:.3f} ms "
                f"| **{r['speedup']:.2f}x** | {r['fused_gbs']:.0f} GB/s "
                f"| {r['fused_pct_of_measured_peak']:.0f}% |"
            )
    if not any_row:
        return "_No runs recorded yet. Run `make bench`._"
    return "\n".join(lines)


def _dispatch_bound_note(runs: list[dict]) -> str:
    rows = [
        (run["device"]["device_name"], r)
        for run in runs
        for r in run["results"]
        if r.get("dispatch_bound")
    ]
    if not rows:
        return ""
    floors = {
        run["device"]["device_name"]: run.get("dispatch_floor_ms", 0.0) for run in runs
    }
    devs = ", ".join(f"{d} ({f * 1e3:.0f} us)" for d, f in floors.items() if f)
    return (
        f"\n{len(rows)} measurements landed within 2x of the launch floor "
        f"({devs}) and are excluded from the tables above. At those shapes the "
        "number describes the runtime's submission path, not the kernel. "
        "Decode-shaped work has to be judged end-to-end or with GPU counters; "
        "see [docs/METHOD.md](docs/METHOD.md).\n"
    )


def _headline(runs: list[dict]) -> str:
    best: tuple[float, str] | None = None
    for run in runs:
        name = run["device"]["device_name"]
        for r in run["results"]:
            if r.get("dispatch_bound") or r["regime"] != "prefill":
                continue
            cand = (
                r["speedup"],
                f"`{r['op']}` at {r['rows']}x{r['width']} on {name}: "
                f"**{r['speedup']:.2f}x** over eager, reaching {r['fused_gbs']:.0f} GB/s "
                f"({r['fused_pct_of_measured_peak']:.0f}% of measured copy bandwidth)",
            )
            if best is None or cand[0] > best[0]:
                best = cand
    return "" if best is None else f"Best measured result -- {best[1]}.\n"


def render(runs: list[dict]) -> str:
    if not runs:
        return (
            f"{BEGIN}\n\n_No benchmark runs recorded yet. "
            "Run `make bench` and then `make report`._\n\n"
            f"{END}"
        )
    parts = [
        BEGIN,
        "",
        "<!-- Generated by `python -m hag.report`. Do not edit by hand. -->",
        "",
        _headline(runs),
        "### Environment",
        "",
        _env_table(runs),
        "",
        "### Prefill regime (batched, memory system saturated)",
        "",
        _results_table(runs, "prefill"),
        "",
        _dispatch_bound_note(runs),
        END,
    ]
    return "\n".join(parts)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--readme", default=str(REPO / "README.md"))
    ap.add_argument("--results", default=str(REPO / "results"))
    ap.add_argument("--check", action="store_true", help="exit 1 if the README is stale")
    args = ap.parse_args()

    readme = Path(args.readme)
    text = readme.read_text()
    if BEGIN not in text or END not in text:
        raise SystemExit(f"{readme} is missing the {BEGIN} / {END} markers")

    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    updated = head + render(load_runs(Path(args.results))) + tail

    if args.check:
        if updated != text:
            print("README results tables are stale; run `make report`.", file=sys.stderr)
            raise SystemExit(1)
        print("README is up to date with results/.")
        return

    readme.write_text(updated)
    print(f"updated {readme}")


if __name__ == "__main__":
    main()
